### ISSUE TITLE
Marker map leaflet

### ISSUE THREAD

**Issue by fredericmineur** [iobis/small-data#8]
Hello guys, I was wondering if you could help me to change the markers on the map. (the idea is to have different markers for different time periods). However, I'm unsuccessful even at changing the current default marker
The script is on species_occurrences/occurrences.html.twig
![image](https://user-images.githubusercontent.com/15698059/45303379-9abbc780-b50d-11e8-800c-e27bfc903a9a.png)
(NB the asset function redirect to the public directory....I tried with  and without quotes)
In the case above, creating the var greenIcon prevents the display of the map (even when the icon option is not set in the var marker). 
When trying the leaflet tutorial (https://leafletjs.com/examples/custom-icons/), the map is still displayed, but only with the default blue icons...
I know it's certainly a stupid mistake on my side...

**Comment by pieterprovoost** [comment]
@fredericmineur Given the issues with had with deploying locally, would you mind deploying the app to the DigitalOcean server so we can diagnose any issues without spending too much time setting everything up? If you like I can reset the server so you can start with a clean slate.

**Comment by fredericmineur** [comment]
@pieterprovoost
Yes, that would be the best solution.
I don't mind trying. But I have to confess that my experience with servers is very close to null. When I installed some feature on the server, I was navigating quite blindly.
Our only experience during the master was to upload local files through Filezilla to a server that had been nicely setup for us.... 
I would need someone "to hold my hand" for the the DigitalOcean server
Can we have as skype/phone conversation at some point?
Cheers

**Comment by pieterprovoost** [comment]
@fredericmineur Some pointers:

- How to connect to your server over SSH: https://www.digitalocean.com/docs/droplets/how-to/connect-with-ssh/
- How to add your SSH key: https://www.digitalocean.com/docs/droplets/how-to/add-ssh-keys/
- How to transfer files: https://www.digitalocean.com/community/tutorials/how-to-use-filezilla-to-transfer-and-manage-files-securely-on-your-vps
- Instead of transferring files, you probably want to pull them right from GitHub: https://help.github.com/articles/cloning-a-repository/
- If you don't want to enter your GitHub credentials for every action, generate an SSH key on the server and add it to GitHub: 
  - `ssh-keygen -t rsa` (keep hitting enter)
  - copy the contents of `~/.ssh/id_rsa.pub` and add it in GitHub (Settings > SSH and GPH keys)
